FORMATO JSON
-------------
Il formato *json* rappresenta bene una *struttura dati gerarchica*. Quando la si vuole visualizzare in tabella ci sono delle parti che si ripetono. Ricordarisi una tabella per i comuni italiani ( si ripete sempre la regione e la provincia per i comuni appartenenti alla stessa provinci) oppure in un report una serie di costi che appartengono ad una stessa famiglia , tipo costi per viaggi, oppure incassi per interventi tecnici(sviluppare meglio)

In [1]:
import pandas as pd 
import numpy as np 
import json

print ('Version Panda=',pd.__version__)
print ('Version Numpy=',np.__version__)
print ('Version json=',json.__version__)

Version Panda= 0.22.0
Version Numpy= 1.14.2
Version json= 2.0.9

In [3]:
dati = '_sigfox_allan_2018_mini.json'

In [4]:
#lettura dati json
json_data = pd.read_json(dati, orient ='columns')
json_data

                                             results
0  {'statement_id': 0, 'series': [{'name': 'C3B2B...

In [5]:
df = pd.DataFrame.from_dict(json_data)
df.head()

                                             results
0  {'statement_id': 0, 'series': [{'name': 'C3B2B...

In [6]:
#serializzazione dati json
ser_json = json_data.to_json(orient="columns")
ser_json

'{"results":{"0":{"statement_id":0,"series":[{"name":"C3B2B","columns":["time","avgSnr","humidity","latitude","light","longitude","pressure","rssi","seqNumber","snr","station","temperature"],"values":[["2018-03-26T00:06:08.686676335Z",52.08,6010,42,null,13,null,-132,"918",18.79,"12A4",9.6],["2018-03-26T00:19:11.593121104Z",52.05,6010,42,null,12,null,-136,"920",15.47,"263D",9.7],["2018-03-26T00:32:14.630254897Z",52.04,6010,42,null,12,null,-135,"922",16.42,"122E",9.5],["2018-03-26T00:45:17.638763852Z",52.01,6010,42,null,13,null,-133,"924",18.13,"12A4",9.6],["2018-03-26T00:58:20.617077509Z",52.01,6110,42,null,12,null,-133,"926",18.05,"12A7",9.2],["2018-03-26T01:11:23.607581655Z",51.97,6110,42,null,13,null,-127,"928",23.74,"264D",9.3],["2018-03-26T01:24:26.568706637Z",52.04,6110,42,null,12,null,-126,"930",25.26,"1296",9.3],["2018-03-26T01:37:29.620999383Z",52.11,6110,42,null,12,null,-99,"932",51.78,"262D",9.1],["2018-03-26T01:50:32.50910401Z",52.14,6210,42,null,13,null,-133,"934",18.39,"12A4",9.2],["2018-03-26T02:03:35.593729069Z",52.09,6210,42,null,12,null,-136,"936",14.79,"122E",8.9],["2018-03-26T02:16:38.541092774Z",52.14,6210,42,null,12,null,-136,"938",14.79,"263D",8.8],["2018-03-26T02:29:41.604940851Z",52.19,6210,42,null,12,null,-135,"940",15.73,"263D",8.9],["2018-03-26T02:42:44.682178499Z",52.2,6210,42,null,13,null,-127,"942",24.17,"264D",8.8],["2018-03-26T02:55:47.665765935Z",52.22,6210,42,null,12,null,-133,"944",18.05,"263D",8.7],["2018-03-26T03:08:50.656221396Z",52.25,6210,42,null,13,null,-128,"946",23.22,"264D",8.8],["2018-03-26T03:21:53.605270175Z",52.27,6210,42,null,13,null,-132,"948",19.52,"12A4",8.7],["2018-03-26T03:34:56.649745296Z",52.32,6210,42,null,12,null,-132,"950",18.71,"263D",8.6],["2018-03-26T03:47:59.845902226Z",52.37,6310,42,null,13,null,-128,"952",23.06,"264D",8.5],["2018-03-26T04:01:02.729020625Z",52.38,6310,42,null,12,null,-138,"954",13.36,"122E",8.3],["2018-03-26T04:14:05.673127183Z",52.44,6310,42,null,12,null,-98,"956",52.92,"262D",8.3],["2018-03-26T04:27:08.63496023Z",52.46,6410,42,null,13,null,-130,"958",20.77,"264D",8.2],["2018-03-26T04:40:12.059034973Z",52.5,6410,42,null,13,null,-133,"960",17.99,"12A4",8.2],["2018-03-26T04:53:14.675027909Z",52.48,6410,42,null,13,null,-132,"962",18.97,"2631",8.1],["2018-03-26T05:06:17.626054058Z",52.41,6410,42,null,12,null,-135,"964",16.22,"122E",8.1],["2018-03-26T05:19:20.642502904Z",52.36,6510,42,null,13,null,-127,"966",23.82,"264D",8],["2018-03-26T05:32:24.335071981Z",52.35,6610,42,null,13,null,-131,"968",20.48,"264D",7.9],["2018-03-26T05:45:27.682764296Z",52.4,6610,42,null,12,null,-127,"970",24.03,"1296",7.8],["2018-03-26T05:58:30.60130418Z",52.34,6610,42,null,12,null,-133,"972",18.4,"12A7",7.9],["2018-03-26T06:11:33.810211244Z",52.33,6510,42,null,12,null,-99,"974",52.16,"262D",8.2],["2018-03-26T06:24:36.66092617Z",52.28,6410,42,null,13,null,-129,"976",22.16,"2631",8.3],["2018-03-26T06:37:39.640335076Z",52.36,6410,42,null,13,null,-135,"978",16.14,"2631",8.4],["2018-03-26T06:50:42.632471191Z",52.29,6410,42,null,13,null,-126,"980",24.96,"264D",8.8],["2018-03-26T07:03:45.836310127Z",52.15,6310,42,null,13,null,-137,"982",14,"1264",9.6],["2018-03-26T07:16:48.597073225Z",52.15,6110,42,null,13,null,-132,"984",18.75,"12A4",10.1],["2018-03-26T07:29:51.549086063Z",52.11,6010,42,null,13,null,-132,"986",19.11,"2631",11],["2018-03-26T07:42:54.611503337Z",52.24,5910,42,null,13,null,-135,"988",16.51,"2631",11.3],["2018-03-26T07:55:57.577529539Z",52.29,5410,42,null,13,null,-128,"990",23.32,"264D",16.3],["2018-03-26T08:09:00.563067646Z",52.46,5410,42,null,13,null,-131,"992",19.83,"2631",21.1],["2018-03-26T08:22:03.612338814Z",52.48,4410,42,null,13,null,-130,"994",20.93,"1282",21.5],["2018-03-26T08:35:06.642136067Z",52.51,4410,42,null,12,null,-132,"996",18.79,"1296",21.5],["2018-03-26T08:48:09.68327388Z",52.59,4410,42,null,12,null,-138,"998",12.96,"263D",22.6],["2018-03-26T09:01:12.772709381Z",52.61,4410,42,null,12,null,-138,"1000",12.77,"263D",21.1],["2018-03-26T09:14:15.752299821Z",52.5,4210,42,null,13,null,-125,"1002",25.7,"264D",22.8],["2018-03-26T09:27:18.75762022Z",52.56,4610,42,null,13,null,-139,"1004",11.96,"1264",18.5],["2018-03-26T09:40:21.888459276Z",52.55,4810,42,null,13,null,-133,"1006",17.99,"12A4",17.6],["2018-03-26T09:53:24.932064313Z",52.42,5010,42,null,12,null,-134,"1008",17.02,"263D",17.1],["2018-03-26T10:06:29.064989698Z",52.35,5110,42,null,12,null,-139,"1010",12.15,"263D",17.2],["2018-03-26T10:19:30.889117665Z",52.14,5310,42,null,13,null,-133,"1012",18.11,"12A4",17.2],["2018-03-26T10:32:33.765569544Z",51.95,5410,42,null,12,null,-138,"1014",13.59,"12A7",17.1],["2018-03-26T10:45:36.579616584Z",51.72,5410,42,null,13,null,-133,"1016",17.82,"264D",16.7],["2018-03-26T10:58:39.706081725Z",51.5,5510,42,null,12,null,-102,"1018",49.55,"262D",17],["2018-03-26T11:11:42.75261761Z",51.43,5210,42,null,12,null,-134,"1020",17.21,"12A7",17.1],["2018-03-26T11:24:45.765580761Z",51.34,5110,42,null,12,null,-135,"1022",15.62,"263D",16.6],["2018-03-26T11:37:48.786684257Z",51.31,5410,42,null,12,null,-137,"1024",13.78,"263D",17.3],["2018-03-26T11:50:51.726311381Z",51.25,5310,42,null,13,null,-130,"1026",21.05,"264D",18.2],["2018-03-26T12:03:54.729644914Z",51.06,5010,42,null,12,null,-135,"1028",16.35,"1315",17.7],["2018-03-26T12:16:57.810690226Z",50.97,5210,42,null,13,null,-132,"1030",18.93,"12A4",17.1],["2018-03-26T12:30:00.810335805Z",51.05,5210,42,null,13,null,-131,"1032",19.95,"2631",16.6],["2018-03-26T12:43:04.032476941Z",51.07,5610,42,null,12,null,-135,"1034",15.81,"1315",16.3],["2018-03-26T12:56:06.674568908Z",51.15,5710,42,null,12,null,-139,"1036",12.54,"263D",15.9],["2018-03-26T13:09:10.376314531Z",51.16,6210,42,null,13,null,-131,"1038",20.25,"264D",15.7],["2018-03-26T13:22:13.003603117Z",51.18,6710,42,null,12,null,-136,"1040",14.72,"2632",14.4],["2018-03-26T13:35:15.777504532Z",51.19,6910,42,null,12,null,-100,"1042",50.96,"262D",13.8],["2018-03-26T13:48:18.839912632Z",51.19,6810,42,null,12,null,-135,"1044",16.53,"1293",13.8],["2018-03-26T14:01:21.608096308Z",51.2,6610,42,null,13,null,-135,"1046",16.02,"2631",14.2],["2018-03-26T14:14:24.653848683Z",51.19,6310,42,null,12,null,-137,"1048",14.24,"263D",14.5],["2018-03-26T14:27:27.788706114Z",51.19,6110,42,null,12,null,-99,"1050",51.89,"262D",14.7],["2018-03-26T14:40:30.949761779Z",51.28,6110,42,null,13,null,-133,"1052",17.73,"2631",14.9],["2018-03-26T14:53:33.904177777Z",51.34,6110,42,null,13,null,-139,"1054",12.02,"1264",15.2],["2018-03-26T15:06:36.795369381Z",51.35,6110,42,null,12,null,-140,"1056",11.12,"2632",15.2],["2018-03-26T15:19:39.87227568Z",51.34,6110,42,null,13,null,-135,"1058",16.09,"12A4",15.2],["2018-03-26T15:32:42.632408812Z",51.34,5910,42,null,13,null,-128,"1060",22.96,"264D",15.8],["2018-03-26T15:45:45.692586628Z",51.43,6010,42,null,12,null,-138,"1062",13.28,"1293",15.8],["2018-03-26T15:58:48.596623942Z",51.56,6010,42,null,13,null,-140,"1064",11.26,"2631",16.4],["2018-03-26T16:11:51.880197361Z",51.53,5810,42,null,12,null,-99,"1066",51.75,"262D",16.3],["2018-03-26T16:24:54.564653148Z",51.56,5810,42,null,13,null,-131,"1068",20.55,"264D",15.6],["2018-03-26T16:37:57.710903793Z",51.54,6010,42,null,13,null,-131,"1070",19.66,"264D",15.2],["2018-03-26T16:51:00.798521156Z",51.6,6110,42,null,13,null,-137,"1072",13.75,"1264",14.7],["2018-03-26T17:04:03.749560607Z",51.56,6210,42,null,12,null,-133,"1074",17.68,"12A7",14.4],["2018-03-26T17:17:06.707714638Z",51.64,6310,42,null,13,null,-136,"1076",15.27,"12A4",14.1],["2018-03-26T17:30:09.721224314Z",51.64,6410,42,null,12,null,-134,"1078",16.99,"122E",14],["2018-03-26T17:43:12.897570281Z",51.61,6410,42,null,12,null,-139,"1080",12.59,"1293",13.6],["2018-03-26T17:56:15.619524231Z",51.57,6410,42,null,12,null,-136,"1082",15.6,"1293",13.5],["2018-03-26T18:09:19.247817253Z",51.56,6410,42,null,12,null,-138,"1084",13.43,"1293",13.2],["2018-03-26T18:22:22.172451097Z",51.52,6410,42,null,13,null,-131,"1086",20.49,"264D",12.9],["2018-03-26T18:35:24.852319912Z",51.5,6810,42,null,13,null,-133,"1088",18.03,"2631",12.8],["2018-03-26T18:48:35.114727317Z",51.52,6910,42,null,13,null,-128,"1090",22.78,"1282",12.9]]}]}}}'

In [21]:
#parsing json string
parsed_json = json.loads(ser_json)
parsed_json

{'results': {'0': {'statement_id': 0,
   'series': [{'name': 'C3B2B',
     'columns': ['time',
      'avgSnr',
      'humidity',
      'latitude',
      'light',
      'longitude',
      'pressure',
      'rssi',
      'seqNumber',
      'snr',
      'station',
      'temperature'],
     'values': [['2018-03-26T00:06:08.686676335Z',
       52.08,
       6010,
       42,
       None,
       13,
       None,
       -132,
       '918',
       18.79,
       '12A4',
       9.6],
      ['2018-03-26T00:19:11.593121104Z',
       52.05,
       6010,
       42,
       None,
       12,
       None,
       -136,
       '920',
       15.47,
       '263D',
       9.7],
      ['2018-03-26T00:32:14.630254897Z',
       52.04,
       6010,
       42,
       None,
       12,
       None,
       -135,
       '922',
       16.42,
       '122E',
       9.5],
      ['2018-03-26T00:45:17.638763852Z',
       52.01,
       6010,
       42,
       None,
       13,
       None,
       -133,
       '924',
       18.13,
       '12A4',
       9.6],
      ['2018-03-26T00:58:20.617077509Z',
       52.01,
       6110,
       42,
       None,
       12,
       None,
       -133,
       '926',
       18.05,
       '12A7',
       9.2],
      ['2018-03-26T01:11:23.607581655Z',
       51.97,
       6110,
       42,
       None,
       13,
       None,
       -127,
       '928',
       23.74,
       '264D',
       9.3],
      ['2018-03-26T01:24:26.568706637Z',
       52.04,
       6110,
       42,
       None,
       12,
       None,
       -126,
       '930',
       25.26,
       '1296',
       9.3],
      ['2018-03-26T01:37:29.620999383Z',
       52.11,
       6110,
       42,
       None,
       12,
       None,
       -99,
       '932',
       51.78,
       '262D',
       9.1],
      ['2018-03-26T01:50:32.50910401Z',
       52.14,
       6210,
       42,
       None,
       13,
       None,
       -133,
       '934',
       18.39,
       '12A4',
       9.2],
      ['2018-03-26T02:03:35.593729069Z',
       52.09,
       6210,
       42,
       None,
       12,
       None,
       -136,
       '936',
       14.79,
       '122E',
       8.9],
      ['2018-03-26T02:16:38.541092774Z',
       52.14,
       6210,
       42,
       None,
       12,
       None,
       -136,
       '938',
       14.79,
       '263D',
       8.8],
      ['2018-03-26T02:29:41.604940851Z',
       52.19,
       6210,
       42,
       None,
       12,
       None,
       -135,
       '940',
       15.73,
       '263D',
       8.9],
      ['2018-03-26T02:42:44.682178499Z',
       52.2,
       6210,
       42,
       None,
       13,
       None,
       -127,
       '942',
       24.17,
       '264D',
       8.8],
      ['2018-03-26T02:55:47.665765935Z',
       52.22,
       6210,
       42,
       None,
       12,
       None,
       -133,
       '944',
       18.05,
       '263D',
       8.7],
      ['2018-03-26T03:08:50.656221396Z',
       52.25,
       6210,
       42,
       None,
       13,
       None,
       -128,
       '946',
       23.22,
       '264D',
       8.8],
      ['2018-03-26T03:21:53.605270175Z',
       52.27,
       6210,
       42,
       None,
       13,
       None,
       -132,
       '948',
       19.52,
       '12A4',
       8.7],
      ['2018-03-26T03:34:56.649745296Z',
       52.32,
       6210,
       42,
       None,
       12,
       None,
       -132,
       '950',
       18.71,
       '263D',
       8.6],
      ['2018-03-26T03:47:59.845902226Z',
       52.37,
       6310,
       42,
       None,
       13,
       None,
       -128,
       '952',
       23.06,
       '264D',
       8.5],
      ['2018-03-26T04:01:02.729020625Z',
       52.38,
       6310,
       42,
       None,
       12,
       None,
       -138,
       '954',
       13.36,
       '122E',
       8.3],
      ['2018-03-26T04:14:05.673127183Z',
       52.44,
       6310,
       42,
       None,
       12,
       None,
       -98,
       '956',
       52.92,
       '262D',
       8.3],
      ['2018-03-26T04:27:08.63496023Z',
       52.46,
       6410,
       42,
       None,
       13,
       None,
       -130,
       '958',
       20.77,
       '264D',
       8.2],
      ['2018-03-26T04:40:12.059034973Z',
       52.5,
       6410,
       42,
       None,
       13,
       None,
       -133,
       '960',
       17.99,
       '12A4',
       8.2],
      ['2018-03-26T04:53:14.675027909Z',
       52.48,
       6410,
       42,
       None,
       13,
       None,
       -132,
       '962',
       18.97,
       '2631',
       8.1],
      ['2018-03-26T05:06:17.626054058Z',
       52.41,
       6410,
       42,
       None,
       12,
       None,
       -135,
       '964',
       16.22,
       '122E',
       8.1],
      ['2018-03-26T05:19:20.642502904Z',
       52.36,
       6510,
       42,
       None,
       13,
       None,
       -127,
       '966',
       23.82,
       '264D',
       8],
      ['2018-03-26T05:32:24.335071981Z',
       52.35,
       6610,
       42,
       None,
       13,
       None,
       -131,
       '968',
       20.48,
       '264D',
       7.9],
      ['2018-03-26T05:45:27.682764296Z',
       52.4,
       6610,
       42,
       None,
       12,
       None,
       -127,
       '970',
       24.03,
       '1296',
       7.8],
      ['2018-03-26T05:58:30.60130418Z',
       52.34,
       6610,
       42,
       None,
       12,
       None,
       -133,
       '972',
       18.4,
       '12A7',
       7.9],
      ['2018-03-26T06:11:33.810211244Z',
       52.33,
       6510,
       42,
       None,
       12,
       None,
       -99,
       '974',
       52.16,
       '262D',
       8.2],
      ['2018-03-26T06:24:36.66092617Z',
       52.28,
       6410,
       42,
       None,
       13,
       None,
       -129,
       '976',
       22.16,
       '2631',
       8.3],
      ['2018-03-26T06:37:39.640335076Z',
       52.36,
       6410,
       42,
       None,
       13,
       None,
       -135,
       '978',
       16.14,
       '2631',
       8.4],
      ['2018-03-26T06:50:42.632471191Z',
       52.29,
       6410,
       42,
       None,
       13,
       None,
       -126,
       '980',
       24.96,
       '264D',
       8.8],
      ['2018-03-26T07:03:45.836310127Z',
       52.15,
       6310,
       42,
       None,
       13,
       None,
       -137,
       '982',
       14,
       '1264',
       9.6],
      ['2018-03-26T07:16:48.597073225Z',
       52.15,
       6110,
       42,
       None,
       13,
       None,
       -132,
       '984',
       18.75,
       '12A4',
       10.1],
      ['2018-03-26T07:29:51.549086063Z',
       52.11,
       6010,
       42,
       None,
       13,
       None,
       -132,
       '986',
       19.11,
       '2631',
       11],
      ['2018-03-26T07:42:54.611503337Z',
       52.24,
       5910,
       42,
       None,
       13,
       None,
       -135,
       '988',
       16.51,
       '2631',
       11.3],
      ['2018-03-26T07:55:57.577529539Z',
       52.29,
       5410,
       42,
       None,
       13,
       None,
       -128,
       '990',
       23.32,
       '264D',
       16.3],
      ['2018-03-26T08:09:00.563067646Z',
       52.46,
       5410,
       42,
       None,
       13,
       None,
       -131,
       '992',
       19.83,
       '2631',
       21.1],
      ['2018-03-26T08:22:03.612338814Z',
       52.48,
       4410,
       42,
       None,
       13,
       None,
       -130,
       '994',
       20.93,
       '1282',
       21.5],
      ['2018-03-26T08:35:06.642136067Z',
       52.51,
       4410,
       42,
       None,
       12,
       None,
       -132,
       '996',
       18.79,
       '1296',
       21.5],
      ['2018-03-26T08:48:09.68327388Z',
       52.59,
       4410,
       42,
       None,
       12,
       None,
       -138,
       '998',
       12.96,
       '263D',
       22.6],
      ['2018-03-26T09:01:12.772709381Z',
       52.61,
       4410,
       42,
       None,
       12,
       None,
       -138,
       '1000',
       12.77,
       '263D',
       21.1],
      ['2018-03-26T09:14:15.752299821Z',
       52.5,
       4210,
       42,
       None,
       13,
       None,
       -125,
       '1002',
       25.7,
       '264D',
       22.8],
      ['2018-03-26T09:27:18.75762022Z',
       52.56,
       4610,
       42,
       None,
       13,
       None,
       -139,
       '1004',
       11.96,
       '1264',
       18.5],
      ['2018-03-26T09:40:21.888459276Z',
       52.55,
       4810,
       42,
       None,
       13,
       None,
       -133,
       '1006',
       17.99,
       '12A4',
       17.6],
      ['2018-03-26T09:53:24.932064313Z',
       52.42,
       5010,
       42,
       None,
       12,
       None,
       -134,
       '1008',
       17.02,
       '263D',
       17.1],
      ['2018-03-26T10:06:29.064989698Z',
       52.35,
       5110,
       42,
       None,
       12,
       None,
       -139,
       '1010',
       12.15,
       '263D',
       17.2],
      ['2018-03-26T10:19:30.889117665Z',
       52.14,
       5310,
       42,
       None,
       13,
       None,
       -133,
       '1012',
       18.11,
       '12A4',
       17.2],
      ['2018-03-26T10:32:33.765569544Z',
       51.95,
       5410,
       42,
       None,
       12,
       None,
       -138,
       '1014',
       13.59,
       '12A7',
       17.1],
      ['2018-03-26T10:45:36.579616584Z',
       51.72,
       5410,
       42,
       None,
       13,
       None,
       -133,
       '1016',
       17.82,
       '264D',
       16.7],
      ['2018-03-26T10:58:39.706081725Z',
       51.5,
       5510,
       42,
       None,
       12,
       None,
       -102,
       '1018',
       49.55,
       '262D',
       17],
      ['2018-03-26T11:11:42.75261761Z',
       51.43,
       5210,
       42,
       None,
       12,
       None,
       -134,
       '1020',
       17.21,
       '12A7',
       17.1],
      ['2018-03-26T11:24:45.765580761Z',
       51.34,
       5110,
       42,
       None,
       12,
       None,
       -135,
       '1022',
       15.62,
       '263D',
       16.6],
      ['2018-03-26T11:37:48.786684257Z',
       51.31,
       5410,
       42,
       None,
       12,
       None,
       -137,
       '1024',
       13.78,
       '263D',
       17.3],
      ['2018-03-26T11:50:51.726311381Z',
       51.25,
       5310,
       42,
       None,
       13,
       None,
       -130,
       '1026',
       21.05,
       '264D',
       18.2],
      ['2018-03-26T12:03:54.729644914Z',
       51.06,
       5010,
       42,
       None,
       12,
       None,
       -135,
       '1028',
       16.35,
       '1315',
       17.7],
      ['2018-03-26T12:16:57.810690226Z',
       50.97,
       5210,
       42,
       None,
       13,
       None,
       -132,
       '1030',
       18.93,
       '12A4',
       17.1],
      ['2018-03-26T12:30:00.810335805Z',
       51.05,
       5210,
       42,
       None,
       13,
       None,
       -131,
       '1032',
       19.95,
       '2631',
       16.6],
      ['2018-03-26T12:43:04.032476941Z',
       51.07,
       5610,
       42,
       None,
       12,
       None,
       -135,
       '1034',
       15.81,
       '1315',
       16.3],
      ['2018-03-26T12:56:06.674568908Z',
       51.15,
       5710,
       42,
       None,
       12,
       None,
       -139,
       '1036',
       12.54,
       '263D',
       15.9],
      ['2018-03-26T13:09:10.376314531Z',
       51.16,
       6210,
       42,
       None,
       13,
       None,
       -131,
       '1038',
       20.25,
       '264D',
       15.7],
      ['2018-03-26T13:22:13.003603117Z',
       51.18,
       6710,
       42,
       None,
       12,
       None,
       -136,
       '1040',
       14.72,
       '2632',
       14.4],
      ['2018-03-26T13:35:15.777504532Z',
       51.19,
       6910,
       42,
       None,
       12,
       None,
       -100,
       '1042',
       50.96,
       '262D',
       13.8],
      ['2018-03-26T13:48:18.839912632Z',
       51.19,
       6810,
       42,
       None,
       12,
       None,
       -135,
       '1044',
       16.53,
       '1293',
       13.8],
      ['2018-03-26T14:01:21.608096308Z',
       51.2,
       6610,
       42,
       None,
       13,
       None,
       -135,
       '1046',
       16.02,
       '2631',
       14.2],
      ['2018-03-26T14:14:24.653848683Z',
       51.19,
       6310,
       42,
       None,
       12,
       None,
       -137,
       '1048',
       14.24,
       '263D',
       14.5],
      ['2018-03-26T14:27:27.788706114Z',
       51.19,
       6110,
       42,
       None,
       12,
       None,
       -99,
       '1050',
       51.89,
       '262D',
       14.7],
      ['2018-03-26T14:40:30.949761779Z',
       51.28,
       6110,
       42,
       None,
       13,
       None,
       -133,
       '1052',
       17.73,
       '2631',
       14.9],
      ['2018-03-26T14:53:33.904177777Z',
       51.34,
       6110,
       42,
       None,
       13,
       None,
       -139,
       '1054',
       12.02,
       '1264',
       15.2],
      ['2018-03-26T15:06:36.795369381Z',
       51.35,
       6110,
       42,
       None,
       12,
       None,
       -140,
       '1056',
       11.12,
       '2632',
       15.2],
      ['2018-03-26T15:19:39.87227568Z',
       51.34,
       6110,
       42,
       None,
       13,
       None,
       -135,
       '1058',
       16.09,
       '12A4',
       15.2],
      ['2018-03-26T15:32:42.632408812Z',
       51.34,
       5910,
       42,
       None,
       13,
       None,
       -128,
       '1060',
       22.96,
       '264D',
       15.8],
      ['2018-03-26T15:45:45.692586628Z',
       51.43,
       6010,
       42,
       None,
       12,
       None,
       -138,
       '1062',
       13.28,
       '1293',
       15.8],
      ['2018-03-26T15:58:48.596623942Z',
       51.56,
       6010,
       42,
       None,
       13,
       None,
       -140,
       '1064',
       11.26,
       '2631',
       16.4],
      ['2018-03-26T16:11:51.880197361Z',
       51.53,
       5810,
       42,
       None,
       12,
       None,
       -99,
       '1066',
       51.75,
       '262D',
       16.3],
      ['2018-03-26T16:24:54.564653148Z',
       51.56,
       5810,
       42,
       None,
       13,
       None,
       -131,
       '1068',
       20.55,
       '264D',
       15.6],
      ['2018-03-26T16:37:57.710903793Z',
       51.54,
       6010,
       42,
       None,
       13,
       None,
       -131,
       '1070',
       19.66,
       '264D',
       15.2],
      ['2018-03-26T16:51:00.798521156Z',
       51.6,
       6110,
       42,
       None,
       13,
       None,
       -137,
       '1072',
       13.75,
       '1264',
       14.7],
      ['2018-03-26T17:04:03.749560607Z',
       51.56,
       6210,
       42,
       None,
       12,
       None,
       -133,
       '1074',
       17.68,
       '12A7',
       14.4],
      ['2018-03-26T17:17:06.707714638Z',
       51.64,
       6310,
       42,
       None,
       13,
       None,
       -136,
       '1076',
       15.27,
       '12A4',
       14.1],
      ['2018-03-26T17:30:09.721224314Z',
       51.64,
       6410,
       42,
       None,
       12,
       None,
       -134,
       '1078',
       16.99,
       '122E',
       14],
      ['2018-03-26T17:43:12.897570281Z',
       51.61,
       6410,
       42,
       None,
       12,
       None,
       -139,
       '1080',
       12.59,
       '1293',
       13.6],
      ['2018-03-26T17:56:15.619524231Z',
       51.57,
       6410,
       42,
       None,
       12,
       None,
       -136,
       '1082',
       15.6,
       '1293',
       13.5],
      ['2018-03-26T18:09:19.247817253Z',
       51.56,
       6410,
       42,
       None,
       12,
       None,
       -138,
       '1084',
       13.43,
       '1293',
       13.2],
      ['2018-03-26T18:22:22.172451097Z',
       51.52,
       6410,
       42,
       None,
       13,
       None,
       -131,
       '1086',
       20.49,
       '264D',
       12.9],
      ['2018-03-26T18:35:24.852319912Z',
       51.5,
       6810,
       42,
       None,
       13,
       None,
       -133,
       '1088',
       18.03,
       '2631',
       12.8],
      ['2018-03-26T18:48:35.114727317Z',
       51.52,
       6910,
       42,
       None,
       13,
       None,
       -128,
       '1090',
       22.78,
       '1282',
       12.9]]}]}}}

In [8]:
nomi_tabella = parsed_json['results']['0']['series'][0]['columns']
nomi_tabella

['time',
 'avgSnr',
 'humidity',
 'latitude',
 'light',
 'longitude',
 'pressure',
 'rssi',
 'seqNumber',
 'snr',
 'station',
 'temperature']

In [17]:
valori_tabella =parsed_json['results']['0']['series'][0]['values']
valori_tabella[:7]

[['2018-03-26T00:06:08.686676335Z',
  52.08,
  6010,
  42,
  None,
  13,
  None,
  -132,
  '918',
  18.79,
  '12A4',
  9.6],
 ['2018-03-26T00:19:11.593121104Z',
  52.05,
  6010,
  42,
  None,
  12,
  None,
  -136,
  '920',
  15.47,
  '263D',
  9.7],
 ['2018-03-26T00:32:14.630254897Z',
  52.04,
  6010,
  42,
  None,
  12,
  None,
  -135,
  '922',
  16.42,
  '122E',
  9.5],
 ['2018-03-26T00:45:17.638763852Z',
  52.01,
  6010,
  42,
  None,
  13,
  None,
  -133,
  '924',
  18.13,
  '12A4',
  9.6],
 ['2018-03-26T00:58:20.617077509Z',
  52.01,
  6110,
  42,
  None,
  12,
  None,
  -133,
  '926',
  18.05,
  '12A7',
  9.2],
 ['2018-03-26T01:11:23.607581655Z',
  51.97,
  6110,
  42,
  None,
  13,
  None,
  -127,
  '928',
  23.74,
  '264D',
  9.3],
 ['2018-03-26T01:24:26.568706637Z',
  52.04,
  6110,
  42,
  None,
  12,
  None,
  -126,
  '930',
  25.26,
  '1296',
  9.3]]

In [19]:
#index=['d', 'b', 'a'], columns=['two', 'three']
dftabella=pd.DataFrame(valori_tabella,columns=nomi_tabella)
print(dftabella[:7])

                             time  avgSnr  humidity  latitude light  \
0  2018-03-26T00:06:08.686676335Z   52.08      6010        42  None
1  2018-03-26T00:19:11.593121104Z   52.05      6010        42  None
2  2018-03-26T00:32:14.630254897Z   52.04      6010        42  None
3  2018-03-26T00:45:17.638763852Z   52.01      6010        42  None
4  2018-03-26T00:58:20.617077509Z   52.01      6110        42  None
5  2018-03-26T01:11:23.607581655Z   51.97      6110        42  None
6  2018-03-26T01:24:26.568706637Z   52.04      6110        42  None

   longitude pressure  rssi seqNumber    snr station  temperature
0         13     None  -132       918  18.79    12A4          9.6
1         12     None  -136       920  15.47    263D          9.7
2         12     None  -135       922  16.42    122E          9.5
3         13     None  -133       924  18.13    12A4          9.6
4         12     None  -133       926  18.05    12A7          9.2
5         13     None  -127       928  23.74    264D          9.3
6         12     None  -126       930  25.26    1296          9.3

In [15]:
json_data.head(50)

                                             results
0  {'statement_id': 0, 'series': [{'name': 'C3B2B...

1 La prima fonte di documentazione per Pandas e in particolare per trattare formati Json è : https://pandas.pydata.org/pandas-docs/stable/io.html#reading-json
2 Una buona referenza per trattare pandas è "https://towardsdatascience.com/a-quick-introduction-to-the-pandas-python-library-f1b678f34673"